version: '3.8'

services:
  tts-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: kokoro-tts-api-cpu:latest
    container_name: tts-api
    ports:
      - "8000:8000"
    volumes:
      - ./kokoro-v1_0.pth:/models/kokoro-v1_0.pth
      - ./config.json:/app/config.json
    environment:
      - PORT=8000
      - ENABLE_RATE_LIMITING=true
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis-data:
